banner:
  location: classpath:bootimage/banner.txt
  image:
    location: 
    width: 90
    height: 0
    margin: 2
    invert: true
server:
    # context-path: /myboot 
    session-timeout: 1800
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 80
    uri-encoding: utf-8
security:
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/themeleaf/
    suffix: .html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true   
#mybatis
mybatis-plus:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: 
  typeEnumsPackage:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    #key-generator:
    #逻辑删除配置（下面3个配置）
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    sql-injector:
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    meta-object-handler:
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    #sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false 